server {
    listen 80;
    server_name _;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        # Esta es la línea mágica para React Router
        try_files $uri $uri/ /index.html;
    }

    # Opcional: Optimización para que el navegador guarde en caché 
    # los archivos que no cambian (imágenes, fuentes, etc.)
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}